Documentation to generate Api Docs on Launchpad
canonical/launchpad-manual pull request #119
Opened 2024-09-30 13:40 UTC by simonepelosi

2024-09-30 13:46 UTC, ikoruk requested changes
few suggestions

2024-09-30 13:46 UTC, ikoruk commented on how-to/launchpad-api-docs.rst
> +``social_account`` id. After that we can write ``xls`` code that will append the
do you mean `xsl`?

2024-09-30 13:46 UTC, ikoruk commented on how-to/launchpad-api-docs.rst
> +``wadl-to-refhtml.xls`` file and we should search our ``wadl`` entry using the
search _for_

2024-09-30 13:46 UTC, ikoruk commented on how-to/launchpad-api-docs.rst
> +The command above is responsible to call the
for calling

2024-09-30 13:46 UTC, ikoruk commented on how-to/launchpad-api-docs.rst
> +fresh docs.
Perhaps it would be good to put all the commands you need to run in order.

```
$ rm -rf lib/canonical/launchpad/apidoc
$ make apidoc
```

2024-09-30 13:46 UTC, ikoruk commented on .wordlist.txt
> +xls
xsl?

2024-10-01 06:28 UTC, jugmac00 approved these changes
Looks good! A couple of grammar related comments to apply before merging.

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +the related documentation for the exported field.
```suggestion
the related documentation for the exported fields.
```

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +We can build Api Docs using ``make apidoc`` command: this command will
```suggestion
We can build API docs using ``make apidoc`` command: this command will 
```

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +Note that we should delete the aforementioned folder in order to generate
Can you please use the `.. note::` syntax?

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +``utilities/create-lp-wadl-and-apidoc.py`` script and generate the related
```suggestion
``utilities/create-lp-wadl-and-apidoc.py`` script and generating the related
```

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +This scripts will create the related ``wadl`` and then it will translated to
Either "These scripts" or "This script".

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +This scripts will create the related ``wadl`` and then it will translated to
``wadl`` file

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +To do that we use as template the file called ``wadl-to-refhtml.xsl``: in
```suggestion
For that we use ``wadl-to-refhtml.xsl`` template. In 
```

2024-10-01 06:28 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +Example
great idea to have an example!

2024-10-04 20:42 UTC, jugmac00 approved these changes
Awesome! Ship it!

2024-10-04 20:42 UTC, jugmac00 commented on how-to/launchpad-api-docs.rst
> +This script will create the related ``wadl`` file and then it will translated to
```suggestion
This script will create the related ``wadl`` file and translate it to
```

2024-10-05 12:35 UTC, merged